# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s1FG1QXVKwmG34fs37Fohf0HN8ZzgUU0
"""

print("hello")